apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: aap
  labels:
    team: aap
    komponent: datadeling
spec:
  image: {{image}}
  ingresses:
    - https://aap-api.nav.no
  replicas:
    max: 2
    min: 2
  kafka:
    pool: nav-prod
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  azure:
    application:
      enabled: true
  maskinporten:
    enabled: true
    scopes: # Når du legger til en konsument her, husk å legge inn i Consumers-object
      exposes:
        - name: "afpprivat.read"
          enabled: true
          product: "aap"
          consumers:
            - name: "Fellesordningen for AFP"
              orgno: "987414502"
        - name: "afpoffentlig.read"
          enabled: true
          product: "aap"
          consumers:
            - name: "NAV"
              orgno: "889640782"
            - name: "Statens pensjonskasse"
              orgno: "982583462"
            - name: "Oslo Pensjonsforsikring"
              orgno: "982759412"
            - name: "Storebrand Pensjonstjenester"
              orgno: "931936492"
            - name: "KOMMUNAL LANDSPENSJONSKASSE GJENSIDIG FORSIKRINGSSELSKAP"
              orgno: "938708606"
            - name: "Gabler Pensjonstjenester AS"
              orgno: "916833520"
            - name: "GARANTIKASSEN FOR FISKERE"
              orgno: "974652382"
        - name: "tpordningen.read"
          enabled: true
          product: "aap"
          delegationSource: altinn
          separator: "/"
          consumers:
            - name: "Drammen"
              orgno: "980650383"
            - name: "Arendal"
              orgno: "940380014"
        - name: "tpordningen.read"
          enabled: true
          product: "aap"
          consumers:
            - name: "NAV"
              orgno: "889640782"
            - name: "Statens pensjonskasse"
              orgno: "982583462"
            - name: "Gabler Pensjonstjenester AS"
              orgno: "916833520"
            - name: "Oslo Pensjonsforsikring"
              orgno: "982759412"
            - name: "Storebrand Pensjonstjenester"
              orgno: "931936492"
            - name: "Storebrand Livsforsikring"
              orgno: "958995369"
            - name: "KOMMUNAL LANDSPENSJONSKASSE GJENSIDIG FORSIKRINGSSELSKAP"
              orgno: "938708606"
            - name: "GARANTIKASSEN FOR FISKERE"
              orgno: "974652382"
            - name: "MARITIM PENSJONSKASSE"
              orgno: "940415683"
        - name: "delegertafpoffentlig.read"
          enabled: true
          product: "aap"
          delegationSource: altinn
          consumers:
            - name: "Drammen"
              orgno: "980650383"
            - name: "Arendal"
              orgno: "940380014"
          separator: "/"
  liveness:
    path: /actuator/live
    initialDelay: 1
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: /actuator/ready
    initialDelay: 1
    periodSeconds: 1
    failureThreshold: 60
  prometheus:
    enabled: true
    path: /actuator/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  accessPolicy:
    outbound:
      rules:
        - application: api-intern
          namespace: aap
      external:
        - host: tp-api.prod-fss-pub.nais.io

  env:
    - name: AAP_AUDIENCE
      value: https://aap-api.nav.no
    - name: ALTINN_WELLKNOWN
      value: https://idporten.no/.well-known/openid-configuration
    - name: ALTINN_AUDIENCE
      value: https://idporten.no
    - name: INTEGRASJON_TP_URL
      value: https://tp-api.prod-fss-pub.nais.io
    - name: INTEGRASJON_TP_SCOPE
      value: api://prod-fss.pensjonsamhandling.tp/.default
    - name: SPORINGSLOGG_TOPIC
      value: pensjonsamhandling.public-sporingslogg-loggmeldingmottatt
    - name: SPORINGSLOGG_ENABLED
      value: "true"
    - name: API_INTERN_URL
      value: http://api-intern
    - name: API_INTERN_SCOPE
      value: api://prod-gcp.aap.api-intern/.default
