apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: aap
  labels:
    team: aap
    komponent: datadeling
spec:
  image: {{image}}
  ingresses:
    - https://aap-api.ekstern.dev.nav.no
  replicas:
    max: 2
    min: 1
  kafka:
    pool: nav-dev
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 500Mi
  azure:
    application:
      enabled: true
  maskinporten:
    enabled: true
    scopes: # Når du legger til en konsument her, husk å legge inn i Consumers-object
      exposes:
        - name: "afpprivat.read"
          enabled: true
          product: "aap"
          consumers:
            - name: "NAV"
              orgno: "889640782"
            - name: "Fellesordningen for AFP"
              orgno: "987414502"
            - name: "KOMMUNAL LANDSPENSJONSKASSE GJENSIDIG FORSIKRINGSSELSKAP"
              orgno: "938708606"
        - name: "afpoffentlig.read"
          enabled: true
          product: "aap"
          consumers:
            - name: "NAV"
              orgno: "889640782"
            - name: "Statens pensjonskasse"
              orgno: "982583462"
            - name: "Gabler Pensjonstjenester AS"
              orgno: "916833520"
            - name: "Storebrand pensjonstjenester"
              orgno: "931936492"
            - name: "KOMMUNAL LANDSPENSJONSKASSE GJENSIDIG FORSIKRINGSSELSKAP"
              orgno: "938708606"
            - name: "Oslo Pensjonsforsikring"
              orgno: "982759412"
            - name: "GARANTIKASSEN FOR FISKERE"
              orgno: "974652382"
        - name: "delegertafpoffentlig.read"
          enabled: true
          product: "aap"
          delegationSource: altinn
          consumers:
            - name: "aksio"
              orgno: "927613298"
            - name: "Drammen"
              orgno: "980650383"
            - name: "Arendal"
              orgno: "940380014"
          separator: "/"
        - name: "tpordningen.read"
          enabled: true
          product: "aap"
          consumers:
            - name: "NAV"
              orgno: "889640782"
            - name: "Statens pensjonskasse"
              orgno: "982583462"
            - name: "Gabler Pensjonstjenester AS"
              orgno: "916833520"
            - name: "Storebrand pensjonstjenester"
              orgno: "931936492"
            - name: "KOMMUNAL LANDSPENSJONSKASSE GJENSIDIG FORSIKRINGSSELSKAP"
              orgno: "938708606"
            - name: "Oslo Pensjonsforsikring"
              orgno: "982759412"
            - name: "GARANTIKASSEN FOR FISKERE"
              orgno: "974652382"
  liveness:
    path: /actuator/live
    initialDelay: 1
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: /actuator/ready
    initialDelay: 1
    periodSeconds: 1
    failureThreshold: 60
  prometheus:
    enabled: true
    path: /actuator/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: test-token-provider
        - application: api-intern
          namespace: aap
      external:
        - host: arenaoppslag.dev-fss-pub.nais.io
  env:
    - name: AAP_AUDIENCE
      value: https://aap-api.ekstern.dev.nav.no
    - name: ARENAOPPSLAG_PROXY_BASE_URL
      value: https://arenaoppslag.dev-fss-pub.nais.io
    - name: ARENAOPPSLAG_SCOPE
      value: api://dev-fss.aap.arenaoppslag/.default
    - name: ALTINN_WELLKNOWN
      value: http://test-token-provider/samtykke/.well-known/oauth-authorization-server
    - name: ALTINN_AUDIENCE
      value: https://aap-test-token-provider.intern.dev.nav.no
    - name: INTEGRASJON_TP_URL
      value: https://tp-api-q2.dev-fss-pub.nais.io
    - name: INTEGRASJON_TP_SCOPE
      value: api://dev-fss.pensjonsamhandling.tp-q2/.default
    - name: SPORINGSLOGG_TOPIC
      value: pensjonsamhandling.public-sporingslogg-loggmeldingmottatt-q2
    - name: SPORINGSLOGG_ENABLED
      value: "false"
    - name: API_INTERN_URL
      value: http://api-intern
    - name: API_INTERN_SCOPE
      value: api://dev-gcp.aap.api-intern/.default