apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: aap
  labels:
    team: aap
    komponent: datadeling
spec:
  image: {{image}}
  ingresses:
       - https://aap-api.nav.no
  replicas:
    max: 1
    min: 1
  kafka:
    pool: nav-prod
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  azure:
    application:
      enabled: true
  maskinporten:
    enabled: true
    scopes: # Når du legger til en konsument her, husk å legge inn i Consumers-object
      exposes:
        - name: "afpprivat.read"
          enabled: true
          product: "aap"
          consumers:
            - name: "Fellesordningen for AFP"
              orgno: "987414502"
  liveness:
    path: /actuator/live
    initialDelay: 1
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: /actuator/ready
    initialDelay: 1
    periodSeconds: 1
    failureThreshold: 60
  prometheus:
    enabled: true
    path: /actuator/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: arenaoppslag.prod-fss-pub.nais.io
  env:
    - name: AAP_AUDIENCE
      value: https://aap-api.nav.no
    - name: ARENAOPPSLAG_PROXY_BASE_URL
      value: https://arenaoppslag.prod-fss-pub.nais.io
    - name: ARENAOPPSLAG_SCOPE
      value: api://prod-fss.aap.arenaoppslag/.default
    - name: ALTINN_WELLKNOWN
      value: https://idporten.no/.well-known/openid-configuration
    - name: ALTINN_AUDIENCE
      value: https://idporten.no
    - name: SPORINGSLOGG_TOPIC
      value: pensjonsamhandling.public-sporingslogg-loggmeldingmottatt
    - name: SPORINGSLOGG_ENABLED
      value: "true"