apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: aap
  labels:
    team: aap
  annotations:
    github.url: "https://github.com/navikt/aap-api"
spec:
  image: {{image}}
  outbound:
    rules:
      - application: sink
  ingresses:
    - {{ingress}}
  replicas:
    max: 1
    min: 1
  kafka:
    pool: {{kafka.pool}}
    streams: true
  liveness:
    path: /actuator/live
    initialDelay: 1
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: /actuator/ready
    initialDelay: 1
    periodSeconds: 1
    failureThreshold: 60
  prometheus:
    enabled: true
    path: /actuator/metrics
  secureLogs:
    enabled: true
  env:
    - name: SINK_HOST
      value: http://sink