apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: aap
  labels:
    team: aap
    sub: vedtak
spec:
  image: {{image}}
  ingresses:
    {{#each ingresses as |url|}}
    - {{url}}
    {{/each}}
  replicas:
    max: 1
    min: 1
  kafka:
    pool: {{kafka.pool}}
    streams: true
  resources:
    limits:
      memory: 8Gi
    requests:
      cpu: 500m
      memory: 4Gi
  azure:
    application:
      enabled: true
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - name: "afpprivat.read"
          enabled: true
          product: "aap"
          consumers:
            - name: "NAV"
              orgno: "889640782"
            - name: "Fellesordningen for AFP"
              orgno: "987414502"
  liveness:
    path: /actuator/live
    initialDelay: 1
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: /actuator/ready
    initialDelay: 1
    periodSeconds: 1
    failureThreshold: 60
  prometheus:
    enabled: true
    path: /actuator/metrics
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: test-token-provider
      external:
        - host: {{arenaoppslag.host}}
  env:
    - name: AAP_AUDIENCE
      value: {{audience}}
    - name: ARENAOPPSLAG_PROXY_BASE_URL
      value: {{arenaoppslag.proxyBaseUrl}}
    - name: ARENAOPPSLAG_SCOPE
      value: {{arenaoppslag.scope}}
    - name: ALTINN_WELLKNOWN
      value: {{altinn.wellknown}}
    - name: ALTINN_AUDIENCE
      value: {{altinn.audience}}
