kafka:
  pool: nav-dev

ingresses:
  - https://aap-api.ekstern.dev.nav.no

audience: https://aap-api.ekstern.dev.nav.no

arenaoppslag:
  proxyBaseUrl: https://arenaoppslag.dev-fss-pub.nais.io
  scope: api://dev-fss.aap.arenaoppslag/.default
  host: arenaoppslag.dev-fss-pub.nais.io

altinn:
  host: aap-test-token-provider.intern.dev.nav.no
  wellknown: https://aap-test-token-provider.intern.dev.nav.no/.well-known/oauth-authorization-server