kafka:
  pool: nav-dev

ingresses:
  - https://aap-api.ekstern.dev.nav.no

audience: https://aap-api.ekstern.dev.nav.no

arenaoppslag:
  proxyBaseUrl: https://arenaoppslag.dev-fss-pub.nais.io
  scope: api://dev-fss.aap.arenaoppslag/.default
  host: arenaoppslag.dev-fss-pub.nais.io

altinn:
  wellknown: https://test.maskinporten.no/.well-known/oauth-authorization-server
  audience: https://test.maskinporten.no