openapi: 3.0.3
info:
  version: 1.0.0
  title: Arbeidsavklaringspenger
  description: REST API for NAV sin ytelse AAP.
paths:
  /vedtak/{personident}:
    get:
      summary: Hent siste vedtak om arbeidsavklaringspenger for en gitt person
      security:
        - bearerAuth: []
      parameters:
        - name: personident
          in: query
          schema:
            type: string
      responses:
        200:
          description: 200 description
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vedtak"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Token fra maskinporten

  schemas:
    Vedtak:
      type: object
      properties:
        vedtaksid:
          type: string
          required: true
        innvilget:
          type: boolean
          required: true
        grunnlagsfaktor:
          type: number
          required: true
        vedtaksdato:
          type: string
          format: date
          required: true
        virkningsdato:
          type: string
          format: date
          required: true
        fødselsdato:
          type: string
          format: date
          required: true
  examples:
    Vedtak:
      description: Vedtak om arbeidsavklaringspenger
      value: >
        {
          "vedtaksid" : "10bb101f-a121-4264-a920-47be9cb82c74",
          "innvilget": true,
          "grunnlagsfaktor": 2.43,
          "vedtaksdato": "2022-11-14",
          "virkningsdato" : "2022-11-14",
          "fødselsdato" : "1987-04-28"
        }
