[versions]
netty = "4.2.17.Final"
jackson = "2.22.2"
jackson3 = "3.2.2"
komponenter = "2.0.172"
apiIntern = "0.0.109"
javaJwt = "4.6.0"
kafka = "4.3.1"
prometheus = "1.8.0"

[libraries]
nettyBom = { module = "io.netty:netty-bom", version.ref = "netty" }
jacksonBom = { module = "com.fasterxml.jackson:jackson-bom", version.ref = "jackson" }
jackson3Bom = { module = "tools.jackson:jackson-bom", version.ref = "jackson3" }

kelvinHttpklient = { module = "no.nav.aap.kelvin:httpklient", version.ref = "komponenter" }
kelvinInfrastructure = { module = "no.nav.aap.kelvin:infrastructure", version.ref = "komponenter" }
apiInternKontrakt = { module = "no.nav.aap.api.intern:kontrakt", version.ref = "apiIntern" }

javaJwt = { module = "com.auth0:java-jwt", version.ref = "javaJwt" }
kafkaStreams = { module = "org.apache.kafka:kafka-streams", version.ref = "kafka" }
prometheusMetricsTracerInitializer = { module = "io.prometheus:prometheus-metrics-tracer-initializer", version.ref = "prometheus" }