kafka:
  application-id: ${KAFKA_STREAMS_APPLICATION_ID}
  brokers: ${KAFKA_BROKERS}
  ssl:
    truststorePath: ${KAFKA_TRUSTSTORE_PATH}
    keystorePath: ${KAFKA_KEYSTORE_PATH}
    credstorePsw: ${KAFKA_CREDSTORE_PASSWORD}

oauth:
  maskinporten:
    issuer:
      name: ${MASKINPORTEN_ISSUER_NAME:-issuer}
      discoveryUrl: ${MASKINPORTEN_WELL_KNOWN_URL:-url}
      audience: ${AAP_AUDIENCE:-audience} # same as ingress "https://aap-api.dev.nav.no" and https://aap-api.nav.no
      optionalClaims: "sub,nbf"
    scope:
      vedtak: "nav:aap:vedtak"
