oauth:
  maskinporten:
    jwksUri: ${MASKINPORTEN_JWKS_URI}
    issuer:
      name: ${MASKINPORTEN_ISSUER}
      discoveryUrl: ${MASKINPORTEN_WELL_KNOWN_URL}
      audience: ${AAP_AUDIENCE} # same as ingress "https://aap-api.dev.nav.no" and https://aap-api.nav.no
      optionalClaims: "sub,nbf"
    scope:
      afpprivat: "nav:aap:afpprivat.read"
  samtykke:
    wellknownUrl: ${ALTINN_WELLKNOWN}
    audience: ${ALTINN_AUDIENCE}

sporingslogg:
  enabled: ${SPORINGSLOGG_ENABLED:-true}
  topic: ${SPORINGSLOGG_TOPIC}

arenaoppslag:
  proxyBaseUrl: ${ARENAOPPSLAG_PROXY_BASE_URL}
  scope: ${ARENAOPPSLAG_SCOPE}

azure:
  tokenEndpoint: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
  clientId: ${AZURE_APP_CLIENT_ID}
  clientSecret: ${AZURE_APP_CLIENT_SECRET}

kafka:
  application-id: ${KAFKA_STREAMS_APPLICATION_ID}
  brokers: ${KAFKA_BROKERS}
  ssl:
    truststorePath: ${KAFKA_TRUSTSTORE_PATH}
    keystorePath: ${KAFKA_KEYSTORE_PATH}
    credstorePsw: ${KAFKA_CREDSTORE_PASSWORD}
