kafka:
  application-id: ${KAFKA_STREAMS_APPLICATION_ID}
  brokers: ${KAFKA_BROKERS}
  ssl:
    truststorePath: ${KAFKA_TRUSTSTORE_PATH}
    keystorePath: ${KAFKA_KEYSTORE_PATH}
    credstorePsw: ${KAFKA_CREDSTORE_PASSWORD}

oauth:
  maskinporten:
    jwksUri: ${MASKINPORTEN_JWKS_URI}
    issuer:
      name: ${MASKINPORTEN_ISSUER}
      discoveryUrl: ${MASKINPORTEN_WELL_KNOWN_URL}
      audience: ${AAP_AUDIENCE} # same as ingress "https://aap-api.dev.nav.no" and https://aap-api.nav.no
      optionalClaims: "sub,nbf"
    scope:
      vedtak: "nav:aap:vedtak.read"
