openapi: "3.0.0"
info:
  title: AAP-api
  description: |-
    AAP-API tilbyr AAP informasjon til eksterne konsumenter som enten har hjemmel til å hente 
    AAP informasjon eller et samtykke fra bruker. Konsumenter må logge seg inn med token fra 
    Maskinporten (alle konsumenter) og et Samtykke-token (konsumenter som ikke har hjemmel).
    
    Linker til autentiseringsløsninger
    - [Maskinporten](https://www.digdir.no/felleslosninger/maskinporten/869)
    - [Samtykke](https://www.altinndigital.no/produkter/samtykke/)
  contact:
    name: Richard Borge
    url: https://github.com/navikt/aap-api
    email: richard.borge@nav.no
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/license/mit/
tags:
  - name: fellesordningen
    description: Fellesordningen for AFP (afp.no)
servers:
  - url: https://aap-api.ekstern.dev.nav.no
    description: Test server
paths:
  /fellesordning/vedtak:
    post:
      summary: Hent vedtak
      tags:
        - fellesordningen
      description: Henter vedtak for en person gitt tidspunkt for ønsket uttak av AFP.
      security:
        - maskinporten: []
      parameters:
        - in: header
          name: x-callid
          description: En UUID konsumenten sender inn som brukes til videre logging og feilsøking.
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VedtakRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VedtakResponse'
        '400':
          description: Feil i request
        '401':
          description: Mangler / feil maskinporten token eller samtykke-token
        '403':
          description: Feil scope i maskinporten token
        '404':
          description: Manglende URL / Person ikke funnet
        '500':
          description: Feil på tjeneste, meld fra og send med call-id
components:
  schemas:
    VedtakResponse:
      type: object
      properties:
        personId:
          type: string
          description: Personnummeret til brukeren
          example: 12345678901
        perioder:
          type: array
          description: Perioder med vedtak
          items:
            $ref: '#/components/schemas/VedtakPeriode'
    VedtakPeriode:
      type: object
      properties:
        fraDato:
          type: string
          format: date
          description: Fra dato for perioden
          example: 2021-01-01
        tilDato:
          type: string
          format: date
          nullable: true
          description: Til dato for perioden
          example: 2021-01-31
    VedtakRequest:
      type: object
      properties:
        personId:
          type: string
          description: Personnummeret til brukeren
          example: 12345678901
        datoForOnsketUttakForAFP:
          type: string
          format: date
          description: Dato for ønsket uttak for AFP
          example: 2021-01-01
  securitySchemes:
    maskinporten:
      type: http
      scheme: bearer
      bearerFormat: JWT
