openapi: "3.0.0"
info:
  title: AAP-api
  description: |-
    AAP-API tilbyr AAP informasjon til eksterne konsumenter som enten har hjemmel til å hente 
    AAP informasjon eller et samtykke fra bruker. Konsumenter må logge seg inn med token fra 
    Maskinporten (alle konsumenter) og et Samtykke-token (konsumenter som ikke har hjemmel).
    
    Linker til autentiseringsløsninger
    - [Maskinporten](https://www.digdir.no/felleslosninger/maskinporten/869)
    - [Samtykke](https://www.altinndigital.no/produkter/samtykke/)
    
    Merk at Maskinporten sitt test-token har en veldig kort levetid (29 sekunder), så det
    egner seg dårlig til manuell test, med mindre man er kjapp til å taste. Det er best å
    bruke denne Swagger-dokumentasjonen som en referanse til å lage en automatisert test,
    ikke teste selve oppslaget.
  contact:
    name: Vetle Hollund
    url: https://github.com/navikt/aap-api
    email: vetle.hollund@nav.no
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/license/mit/
tags:
  - name: afp
    description: AFP (avtalefestet pensjon)
servers:
  - url: https://aap-api.ekstern.dev.nav.no
    description: Test server
paths:
  /afp/fellesordningen:
    post:
      summary: Hent perioder med AAP, scopet for privat sektor
      tags:
        - afp
      description: |-
        Henter perioder med vedtak for en person innen gitte datointerval. 

        Scope: `nav:aap:afpprivat.read`
      security:
        - maskinporten: [ ]
      parameters:
        - in: header
          name: x-callid
          description: En UUID konsumenten sender inn som brukes til videre logging og feilsøking.
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PeriodeRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PeriodeResponse'
        '400':
          description: Feil i request
        '401':
          description: Mangler / feil maskinporten token eller samtykke-token
        '403':
          description: Feil scope i maskinporten token
        '404':
          description: Manglende URL / Person ikke funnet
        '500':
          description: Feil på tjeneste, meld fra og send med call-id
  /afp/offentlig:
    post:
      summary: Hent perioder med AAP, scopet for offentlig sektor
      tags:
        - afp
      description: |-
        Henter perioder med vedtak for en person innen gitte datointerval.
        
        Scope: `nav:aap:afpoffentlig.read`
      security:
        - maskinporten: [ ]
      parameters:
        - in: header
          name: x-callid
          description: En UUID konsumenten sender inn som brukes til videre logging og feilsøking.
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PeriodeRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PeriodeResponse'
        '400':
          description: Feil i request
        '401':
          description: Mangler / feil maskinporten token eller samtykke-token
        '403':
          description: Feil scope i maskinporten token
        '404':
          description: Manglende URL / Person ikke funnet
        '500':
          description: Feil på tjeneste, meld fra og send med call-id
  /tp-samhandling:
    post:
      summary: Hent invilget vedtak og alle tilhørende utbetalinger for en person
      tags:
        - tp
      description: |-
        Hent invilget vedtak og alle tilhørende utbetalinger for en person.

        Scope: `nav:aap:tpordningen.read`
        
      security:
        - maskinporten: [ ]
      parameters:
        - in: header
          name: x-callid
          description: En UUID konsumenten sender inn som brukes til videre logging og feilsøking.
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PeriodeRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaksimumRespons'
        '400':
          description: Feil i request
        '401':
          description: Mangler / feil maskinporten token eller samtykke-token
        '403':
          description: Feil scope i maskinporten token
        '404':
          description: Manglende URL / Person ikke funnet
        '500':
          description: Feil på tjeneste, meld fra og send med call-id
components:
  schemas:
    PeriodeResponse:
      type: array
      items:
        $ref: '#/components/schemas/Periode'
    Periode:
      type: object
      properties:
        fraOgMedDato:
          type: string
          format: date
          description: Fra dato for perioden
          example: 2021-01-01
        tilOgMedDato:
          type: string
          format: date
          nullable: true
          description: Til dato for perioden
          example: 2021-01-31
    MaksimumRespons:
      type: array
      description: liste
      items:
        $ref: '#/components/schemas/Vedtak'

    Reduksjon:
        type: object
        properties:
          timerArbeidet:
            type: number
            description: Kode for utbetalingsgrad
            example: 23.5
          annenReduksjon:
            $ref: '#/components/schemas/AnnenReduksjon'
    AnnenReduksjon:
      type: object
      properties:
        sykedager:
          type: number
          description: Antall sykedager
          example: 23
        sentMeldekort:
          type: boolean
          description: Var utbetalingens koblede meldekort sendt sent?
          example: false
        fraver:
            type: number
            description: Antall fraværsdager
            example: 2
    UtbetalingMedMer:
      type: object
      properties:
        periode:
          $ref: '#/components/schemas/Periode'
        reduksjon:
          $ref: '#/components/schemas/Reduksjon'
        belop:
          type: number
          description: Utbetalingsbeløp
          example: 1234.56
        dagsats:
          type: number
          description: Dagsats for utbetalingen
          example: 123.45
        barnetilegg:
          type: number
          description: Barnetillegg for utbetalingen
          example: 123.45
    Vedtak:
      type: object
      properties:
        utbetalinger:
          type: array
          description: Utbetalinger for vedtaket
          items:
            $ref: '#/components/schemas/UtbetalingMedMer'
        dagsats:
          type: number
          description: Dagsats for vedtaket
          example: 123.45
        status:
          type: string
          description: Status for vedtaket
          example: "Innvilget"
        saksnummer:
          type: string
          description: Saksnummer for vedtaket
          example: "123456789"
        vedtaksdato:
          type: string
          format: date
          description: Dato for vedtaket
          example: 2021-01-01
        periode:
          $ref: '#/components/schemas/Periode'
        rettighetsType:
          type: string
          description: Rettighetstype for vedtaket
          enum:
            - "FA"
            - "AU"
            - "UVUP"
            - "IKKE"
            - "SPE"
            - "UA"
          example: "FA"
        beregningsgrunnlag:
          type: number
          description: Beregningsgrunnlag for vedtaket
          example: 123456
    PeriodeRequest:
      type: object
      properties:
        personidentifikator:
          type: string
          description: Personnummeret til brukeren
          example: 12345678901
        fraOgMedDato:
          type: string
          format: date
          description: Start-dato for ønsket uttak av AAP-perioder
          example: 2021-01-01
        tilOgMedDato:
          type: string
          format: date
          description: Slutt-dato for ønsket uttak av AAP-perioder
          example: 2021-01-01
  securitySchemes:
    maskinporten:
      type: http
      scheme: bearer
      bearerFormat: JWT
