GET https://aap-test-token-provider.intern.dev.nav.no/maskinporten/token/afpprivat
Accept: application/json

> {% client.global.set("auth_token", response.body.trim()); %}

###

POST https://aap-api.ekstern.dev.nav.no/afp/fellesordningen
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}
x-callid: 08e61a77-54bd-4156-b343-a283a68abe0e

{
  "personidentifikator": "23047616018",
  "fraOgMedDato": "2020-01-01",
  "tilOgMedDato": "2023-12-31"
}