name: Deploy API

on:
  push:
    branches: [ main ]

permissions: write-all

env:
  IMAGE: europe-north1-docker.pkg.dev/${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}/aap/${{ github.repository }}:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: styfle/cancel-workflow-action@0.12.0
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - uses: gradle/gradle-build-action@v2.11.1
        with:
          arguments: test app:buildFatJar cyclonedxBom --continue --no-daemon

      - uses: dorny/test-reporter@v1.7.0
        if: success() || failure()
        with:
          name: test
          path: "**/build/test-results/test/TEST-*.xml"
          reporter: java-junit
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: nais/docker-build-push@v0
        with:
          team: aap
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          tag: ${{ github.sha }}
          byosbom: app/build/reports/bom.json

  deploy-dev:
    needs: [ build ]
    name: Deploy (dev-gcp)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/app-dev.yml
          PRINT_PAYLOAD: true

  deploy-prod:
    needs: [ build ]
    name: Deploy (prod-gcp)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/app-prod.yml
          PRINT_PAYLOAD: true

